//! Per-user claude execution wrapper.
//!
//! Each WeChat user's reply is generated by a fresh, ephemeral OCI container
//! running on **gVisor (runsc)** — the same threat model as OpenAI's Code
//! Interpreter. weclawbot is just the orchestrator on the host; all the
//! actual file/code handling happens inside the container.
//!
//! Container runtime: **podman + runsc**.
//!   - podman: daemonless, no root required, Docker-CLI compatible
//!   - runsc:  user-space kernel, intercepts all syscalls
//!
//! Linux-only. `preflight()` refuses to start if either binary is missing.

use std::path::PathBuf;
use std::process::Command as StdCommand;

use tokio::process::Command;

use super::Sandbox;
use crate::sandbox::layout;

pub(crate) const PODMAN_BIN: &str = "podman";
const RUNSC_BIN: &str = "runsc";

/// Default image; overridable via `~/.weclawbot/config.json /sandbox/image`.
pub const DEFAULT_IMAGE: &str =
    "ghcr.io/anthropics/weclawbot-sandbox-base:latest";

/// Default container resource limits.
const DEFAULT_MEMORY: &str = "2g";
const DEFAULT_CPUS: &str = "2";
const DEFAULT_PIDS_LIMIT: &str = "512";
/// Where the operator's claude config lands inside the container.
const SANDBOX_HOME: &str = "/home/claude";

#[derive(Debug, Clone)]
pub struct PodmanInfo {
    pub path: PathBuf,
    pub version: String,
}

#[derive(Debug, Clone)]
pub struct RuntimeInfo {
    pub path: PathBuf,
    pub version: String,
    /// Is `runsc` registered as a podman runtime?
    pub registered: bool,
}

pub fn detect_podman() -> Option<PodmanInfo> {
    let out = StdCommand::new(PODMAN_BIN).arg("--version").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let version = String::from_utf8_lossy(&out.stdout).trim().to_string();
    let path = which(PODMAN_BIN).unwrap_or_else(|| PathBuf::from(PODMAN_BIN));
    Some(PodmanInfo { path, version })
}

pub fn detect_runsc() -> Option<RuntimeInfo> {
    let out = StdCommand::new(RUNSC_BIN).arg("--version").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let version = stdout.lines().next().unwrap_or("").trim().to_string();
    let path = which(RUNSC_BIN).unwrap_or_else(|| PathBuf::from(RUNSC_BIN));
    let registered = podman_has_runtime("runsc");
    Some(RuntimeInfo {
        path,
        version,
        registered,
    })
}

/// Check whether `runsc` is declared in any containers.conf the user might use.
///
/// `podman info` only reports the DEFAULT runtime, not the full registered
/// set. We therefore scan the containers.conf files podman reads, in order:
/// user-level → system-level. A match is any line starting with `runsc =`
/// or `"runsc" =` inside an `[engine.runtimes]` section.
fn podman_has_runtime(name: &str) -> bool {
    let user_conf = dirs::home_dir()
        .map(|h| h.join(".config/containers/containers.conf"));
    let system_confs = [
        std::path::PathBuf::from("/etc/containers/containers.conf"),
        std::path::PathBuf::from("/usr/share/containers/containers.conf"),
    ];
    let candidates: Vec<std::path::PathBuf> = user_conf
        .into_iter()
        .chain(system_confs.into_iter())
        .collect();

    for path in candidates {
        let raw = match std::fs::read_to_string(&path) {
            Ok(s) => s,
            Err(_) => continue,
        };
        let mut in_runtimes = false;
        for line in raw.lines() {
            let l = line.trim();
            if l.starts_with('[') {
                in_runtimes = l == "[engine.runtimes]";
                continue;
            }
            if in_runtimes {
                let stripped = l.trim_start_matches('"');
                if stripped.starts_with(&format!("{name} ="))
                    || stripped.starts_with(&format!("{name}\""))
                {
                    return true;
                }
            }
        }
    }
    false
}

/// Pull the sandbox image if not already present. Best-effort during
/// preflight; spawn-time errors will surface if it's still missing.
pub fn ensure_image(image: &str) -> Result<(), String> {
    let exists = StdCommand::new(PODMAN_BIN)
        .args(["image", "exists", image])
        .status()
        .map_err(|e| format!("podman image exists: {e}"))?;
    if exists.success() {
        return Ok(());
    }
    let out = StdCommand::new(PODMAN_BIN)
        .args(["pull", image])
        .output()
        .map_err(|e| format!("podman pull: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "podman pull {image} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

/// Smoke test: spawn a trivial container with runsc to confirm the pipeline
/// works on this host. Returns Ok on exit 0.
pub fn runsc_smoke_test() -> Result<(), String> {
    let out = StdCommand::new(PODMAN_BIN)
        .args([
            "run",
            "--rm",
            "--runtime=runsc",
            "--network=none",
            "docker.io/library/alpine:3",
            "true",
        ])
        .output()
        .map_err(|e| format!("spawn smoke test: {e}"))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "smoke test exit {:?}: {}",
            out.status.code(),
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

/// Build a tokio Command that runs an AI CLI binary inside a per-user
/// gVisor container. Shared by [`build_claude_cmd`] and [`build_codex_cmd`].
///
/// `entrypoint` overrides the image's default ENTRYPOINT (which is `claude`)
/// — pass `None` to keep it (claude), or `Some("codex")` for codex.
fn build_sandbox_cmd(
    sandbox: &Sandbox,
    entrypoint: Option<&str>,
    args: &[&str],
) -> Command {
    let image = sandbox_image();

    let mut cmd = Command::new(PODMAN_BIN);
    cmd.arg("run")
        .arg("--rm")
        .arg("-i") // keep stdin open so we can pipe the prompt into `cli -p`
        // v2.2 L3.2: label container with user_hash so `lifecycle::kill_user_containers`
        // can find + kill running containers when an operator deletes the user.
        // Without this label, deleted users with in-flight AI calls would leave
        // orphan containers running against a non-existent DB row.
        .arg("--label")
        .arg(format!("user={}", sandbox.user_hash))
        .arg("--label")
        .arg("app=weclawbot")
        // Map the host user 1:1 onto the container's user (UID 1000) so
        // bind-mounted files (esp. credentials.json with mode 600) are
        // readable by the in-container user. Without this, rootless podman's
        // userns remapping shows them as owned by root inside.
        .arg("--userns=keep-id:uid=1000,gid=1000")
        .arg("--runtime=runsc")
        .arg("--memory").arg(DEFAULT_MEMORY)
        .arg("--cpus").arg(DEFAULT_CPUS)
        .arg("--pids-limit").arg(DEFAULT_PIDS_LIMIT)
        .arg("--read-only")
        .arg("--tmpfs").arg("/tmp")
        .arg("--tmpfs").arg("/run")
        .arg("--network=bridge")
        .arg("-e").arg(format!("HOME={SANDBOX_HOME}"));

    // Per-user writable $HOME — covers .claude/ AND any sibling state files
    // the AI wants to write (e.g. ~/.claude.json, ~/.cache/, etc.). Without
    // the whole home dir being writable, --read-only on / would block them
    // and the binary exits 1 with EROFS.
    cmd.arg("-v").arg(format!(
        "{}:{SANDBOX_HOME}:rw",
        sandbox.home().display()
    ));
    cmd.arg("-v").arg(format!(
        "{}:/work:rw",
        sandbox.work().display()
    ));
    // Inbound media is read-only inside the container — the AI can read user
    // files but can't tamper with what was forwarded from WeChat.
    cmd.arg("-v").arg(format!(
        "{}:{SANDBOX_HOME}/media:ro",
        sandbox.media().display()
    ));

    // Auth credentials — bind-mounted RW so the sandboxed claude can
    // refresh its own OAuth token when the access token expires
    // (~24h lifetime). Mounted ro would force the sandbox to use a
    // stale token and 401 forever. Refresh is atomic-write in claude-cli
    // so concurrent host/sandbox refresh races resolve to one of two
    // valid token sets — no corruption risk in practice.
    cmd.arg("-v").arg(format!(
        "{}:{SANDBOX_HOME}/.claude/.credentials.json",
        canonical_or(&layout::shared_credentials()).display()
    ));

    cmd.arg("--workdir=/work");

    if let Some(ep) = entrypoint {
        cmd.arg(format!("--entrypoint={ep}"));
    }

    cmd.arg(image);
    for a in args {
        cmd.arg(a);
    }
    cmd
}

/// Build a tokio Command that runs `claude` inside a per-user gVisor
/// container. Uses the image's default ENTRYPOINT.
pub fn build_claude_cmd(sandbox: &Sandbox, claude_args: &[&str]) -> Command {
    build_sandbox_cmd(sandbox, None, claude_args)
}

/// Build a tokio Command that runs `codex` inside the same per-user
/// container. The image must have codex on `$PATH` — the default sandbox
/// image does NOT bundle it; operators who want codex must build a derived
/// image with `npm install -g @openai/codex`.
pub fn build_codex_cmd(sandbox: &Sandbox, codex_args: &[&str]) -> Command {
    build_sandbox_cmd(sandbox, Some("codex"), codex_args)
}

/// Resolve symlinks to canonical paths so podman's mount source is real.
fn canonical_or(p: &std::path::Path) -> PathBuf {
    std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf())
}

/// Image reference actually used at spawn time. Reads `sandbox.image` from
/// `~/.weclawbot/config.json`; falls back to `DEFAULT_IMAGE`.
pub fn sandbox_image() -> String {
    let image = crate::config::Config::load().sandbox.image;
    if image.is_empty() {
        DEFAULT_IMAGE.to_string()
    } else {
        image
    }
}

fn which(name: &str) -> Option<PathBuf> {
    let path_env = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path_env) {
        let candidate = dir.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            if let Ok(meta) = candidate.metadata() {
                if meta.is_file() && meta.permissions().mode() & 0o111 != 0 {
                    return Some(candidate);
                }
            }
        }
    }
    None
}
